### ISSUE TITLE
Why support both file names and stdout?

### ISSUE THREAD

**Issue by bast** [uit-no/sonar#19]
I would like to write to either stdout or to files but not support both. Do we need both? I think we get simpler code and less surprises if we allow either/or. I am not too happy that "-" means stdout. I can do the code change but wanted to check before I go in with the wrecking ball.

**Comment by bast** [comment]
Similarly I would like to require an input directory to the mapper and not assume that no input dir means this dir, following "Explicit is better than implicit".

**Comment by mathiasbockwoldt** [comment]
My idea was to support both so we could have multiple outputs later. If I would have to chose one, I'd go for stdout, since stdout can easily be redirected to file via `>`.

Anyway, using `-` as "marker" for stdout is pretty common in command line tools and even defined in POSIX, see e.g. https://stackoverflow.com/questions/3797795/does-mean-stdout-in-bash (in there is also the link to POSIX, but Stackoverflow is easier to read :wink: ).

I'm fine with requiring an input directory. Feel free to change :smiley:. Or wait until tomorrow, then I can change it.

**Comment by bast** [comment]
Interesting, I did not know about the "-" convention although I have used it in the past. I would also say that if we decide for either/or, then stdout since it is more flexible.

What do you mean by "so we could have multiple outputs later"? (no problem to discuss/reply this tomorrow or later).

I will go ahead with requiring the input directory.
